name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"  # Treat warnings as errors for stricter linting

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Fetch and verify Git checkout state
      - name: Fetch and Verify Git Checkout
        run: |
          git fetch origin
          git checkout main
          git reset --hard origin/main
          git clean -fdx
          git status
          git log -1
          git rev-parse --abbrev-ref HEAD
          find src tests -name '*.rs' -exec stat --format="%n %y %s" {} \;
        shell: bash

      # Install the latest stable Rust toolchain
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.81
          components: rustfmt, clippy

      # Verify Rust version
      - name: Check Rust Version
        run: rustc --version

      # Clean build artifacts
      - name: Clean Build
        run: cargo clean

      # Debug: Print contents, checksums, and metadata
      - name: Debug Source and Test Files
        run: |
          echo "Debugging files at $(date)"
          find src tests -name '*.rs' -exec sh -c 'echo "File: {}"; cat -n "{}"; sha256sum "{}"; stat --format="%n %y %s" "{}"' \;
          echo "Expected src/lib.rs contents:" > expected_lib.rs
          cat src/lib.rs >> expected_lib.rs
          git diff --no-index expected_lib.rs src/lib.rs || true
        shell: bash

      # Clean up temporary debug files
      - name: Clean Up Debug Files
        run: rm -f expected_lib.rs
        shell: bash

      # Check module structure
      - name: Check Module Structure
        run: cargo check
        env:
          RUSTFLAGS: "-Dwarnings"

      # Verify public API
      - name: Verify Public API
        run: cargo publish --dry-run
        env:
          RUSTFLAGS: "-Dwarnings"

      # Check code formatting with rustfmt
      - name: Check Formatting
        run: cargo fmt --check
        continue-on-error: false

      # Run Clippy for static analysis
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        continue-on-error: false

      # Build the project
      - name: Build
        run: cargo build --verbose --all-targets
        env:
          RUSTFLAGS: "-Dwarnings"

      # Run tests
      - name: Run Tests
        run: cargo test --verbose
        env:
          RUSTFLAGS: "-Dwarnings"

      # Verify benchmarks compile
      - name: Check Benchmarks
        run: cargo bench --no-run
        env:
          RUSTFLAGS: "-Dwarnings"
