name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"  # Treat warnings as errors for stricter linting

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Verify Git checkout state
      - name: Verify Git Checkout
        run: |
          git status
          git log -1
        shell: bash

      # Install the latest stable Rust toolchain
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.81
          components: rustfmt, clippy

      # Verify Rust version
      - name: Check Rust Version
        run: rustc --version

      # Clean build artifacts
      - name: Clean Build
        run: cargo clean

      # Debug: Print contents of all source and test files with line numbers and timestamps
      - name: Debug Source and Test Files
        run: |
          echo "Debugging source and test files at $(date)"
          find src tests -name '*.rs' -exec sh -c 'echo "File: {}"; cat -n "{}"' \;
        shell: bash

      # Check module structure
      - name: Check Module Structure
        run: cargo check
        env:
          RUSTFLAGS: "-Dwarnings"

      # Verify public API
      - name: Verify Public API
        run: cargo publish --dry-run
        env:
          RUSTFLAGS: "-Dwarnings"

      # Check code formatting with rustfmt
      - name: Check Formatting
        run: cargo fmt --check
        continue-on-error: false

      # Run Clippy for static analysis
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        continue-on-error: false

      # Build the project
      - name: Build
        run: cargo build --verbose --all-targets
        env:
          RUSTFLAGS: "-Dwarnings"

      # Run tests
      - name: Run Tests
        run: cargo test --verbose
        env:
          RUSTFLAGS: "-Dwarnings"

      # Verify benchmarks compile (but don't run them)
      - name: Check Benchmarks
        run: cargo bench --no-run
        env:
          RUSTFLAGS: "-Dwarnings"
