name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean Clone Repository
        run: |
          git clone https://github.com/murphsicles/HOKG .
          git checkout main
          git reset --hard origin/main
          git clean -fdx
        shell: bash

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.83
          components: rustfmt

      - name: Check Rust Version
        run: rustc --version

      - name: Clean Build
        run: cargo clean

      - name: Check Formatting
        run: cargo fmt --check
        env:
          RUSTFLAGS: "-Dwarnings"

      - name: Build
        run: cargo build --verbose --all-targets
        env:
          RUSTFLAGS: "-Dwarnings"

  test:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    steps:
      - name: Clean Clone Repository
        run: |
          git clone https://github.com/murphsicles/HOKG .
          git checkout main
          git reset --hard origin/main
          git clean -fdx
        shell: bash

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.83
          components: rustfmt

      - name: Check Rust Version
        run: rustc --version

      - name: Check Repository State
        run: git log -n 3

      - name: Clean Build
        run: cargo clean

      - name: Debug file contents
        run: |
          cat src/lib.rs
          cat tests/integration.rs

      - name: Run Tests
        run: cargo test --verbose
        env:
          RUSTFLAGS: "-Dwarnings"
